### ISSUE TITLE
Convert the date format in recent.rb

### ISSUE THREAD

**Issue by sumitsharma480** [mm53bar/obsidian#1]
Hello Sir, 

Thank you so much @mm53bar  for this wonderful script. Especially the recent.rb and todo.rb . 
This is a **Feature Request**. I just want to change the date format from YYYY-MM-DD in the recent .rb to DD-MM-YYYY . 
I am not a developer. If you could do this, it will be a great help.

Kudos to your efforts. Really appreciate it.

**Comment by mm53bar** [comment]
Sorry @sumitsharma480 but I won't be changing the date format. YYYY-MM-DD is ISO 8601 standard and very common. In addition, it's the default format for Obsidian. I get that other folks might prefer different standards because of regional differences, but I recommend forking the codebase in that case and making the change in your fork.
